import {VideoConfig} from '../src/yukkuri/yukkuriVideoConfig';

export const MyVideoConfig: VideoConfig = {
  sections: [
    {
      title: 'メインセクション',
      bgmSrc: 'bgm/Floraria.mp3',
      bgmVolume: 0.2,
      fromFramesMap: {"0":30,"1":186,"2":303,"3":486,"4":687,"5":855,"6":1149,"7":1327,"8":1592,"9":1795,"10":1936,"11":2221,"12":2314,"13":2571,"14":2642,"15":2734,"16":2933,"17":3238,"18":3376,"19":3492,"20":3604,"21":3742,"22":3934,"23":4066,"24":4182,"25":4351,"26":4539,"27":4749,"28":4865,"29":5060,"30":5298,"31":5471},
      totalFrames: 5892,
      kuchipakuMap: {frames: [], amplitude: []},
      talks: [
        {
          text: '最近、「自社データならラグでしょ」っていう空気がありますよね。',
          speaker: 'ayumi',
          id: 'S001-1',
          audioDurationFrames: 131,
        },
        {
          text: 'でも、実はそうとも限らないんです。',
          speaker: 'ayumi',
          id: 'S001-2',
          audioDurationFrames: 92,
        },
        {
          text: 'まずは、その思い込みを静かにほどいてみましょう。',
          speaker: 'ayumi',
          id: 'S001-3',
          audioDurationFrames: 113,
          pauseAfter: 1.5,
        },
        {
          text: 'よくいただくご相談で、「ラグを入れないといけませんよね？」という声があります。',
          speaker: 'ayumi',
          id: 'S002-1',
          audioDurationFrames: 176,
        },
        {
          text: 'けれど本当は、プロンプトだけで十分に回るケースが多いんです。',
          speaker: 'ayumi',
          id: 'S002-2',
          audioDurationFrames: 143,
        },
        {
          text: 'むしろ、内容がパターン化できるなら、ラグより精度が上がることも珍しくありません。',
          speaker: 'ayumi',
          id: 'S002-3',
          audioDurationFrames: 194,
          pauseAfter: 2.5,
        },
        {
          text: '最初に考えたいのは、「エーアイにデータを全部見てほしいのかどうか」。',
          speaker: 'ayumi',
          id: 'S003-1',
          audioDurationFrames: 153,
        },
        {
          text: 'もし"最初から全部読んだうえで判断してほしい"のであれば、部分検索であるラグはあまり向いていません。',
          speaker: 'ayumi',
          id: 'S003-2',
          audioDurationFrames: 240,
        },
        {
          text: '全文をそのまま読ませるほうが、自然で、確実です。',
          speaker: 'ayumi',
          id: 'S003-3',
          audioDurationFrames: 133,
          pauseAfter: 1.5,
        },
        {
          text: 'そして次に、"入力の上限に収まるかどうか"。',
          speaker: 'ayumi',
          id: 'S004-1',
          audioDurationFrames: 116,
        },
        {
          text: 'ジーピーティーやクロードの10から20万字、ジェミニの100万字以上という上限なら、意外と全部入ってしまいます。',
          speaker: 'ayumi',
          id: 'S004-2',
          audioDurationFrames: 260,
        },
        {
          text: 'しかもコストはほんのわずか。',
          speaker: 'ayumi',
          id: 'S004-3',
          audioDurationFrames: 68,
        },
        {
          text: '複雑なラグを組むより、安く・速く・安定して動くことが多いんです。',
          speaker: 'ayumi',
          id: 'S004-4',
          audioDurationFrames: 187,
          pauseAfter: 1.5,
        },
        {
          text: 'さらにもうひとつ。',
          speaker: 'ayumi',
          id: 'S005-1',
          audioDurationFrames: 46,
        },
        {
          text: '"パターン数はどれくらいか"。',
          speaker: 'ayumi',
          id: 'S005-2',
          audioDurationFrames: 67,
        },
        {
          text: 'もし問い合わせや業務が10から20パターンほどなら、テンプレート化が最適です。',
          speaker: 'ayumi',
          id: 'S005-3',
          audioDurationFrames: 174,
        },
        {
          text: '業界別に作ったプロンプトは使い回しが簡単で、精度も運用性も申し分ありません。',
          speaker: 'ayumi',
          id: 'S005-4',
          audioDurationFrames: 205,
          pauseAfter: 2.5,
        },
        {
          text: 'つまり──全部見たいなら、プロンプトに入れる。',
          speaker: 'ayumi',
          id: 'S006-1',
          audioDurationFrames: 113,
        },
        {
          text: '上限に収まるなら、全文を入れる。',
          speaker: 'ayumi',
          id: 'S006-2',
          audioDurationFrames: 91,
        },
        {
          text: 'パターンが少ないなら、テンプレ化する。',
          speaker: 'ayumi',
          id: 'S006-3',
          audioDurationFrames: 87,
        },
        {
          text: 'この条件がそろえば、ラグは必要ありません。',
          speaker: 'ayumi',
          id: 'S006-4',
          audioDurationFrames: 113,
        },
        {
          text: 'もっとシンプルで、もっと強い選択肢があるからです。',
          speaker: 'ayumi',
          id: 'S006-5',
          audioDurationFrames: 122,
          pauseAfter: 1.5,
        },
        {
          text: 'そもそも、ラグは万能の正義ではありません。',
          speaker: 'ayumi',
          id: 'S007-1',
          audioDurationFrames: 107,
        },
        {
          text: '適材適所でこそ輝く技術なんです。',
          speaker: 'ayumi',
          id: 'S007-2',
          audioDurationFrames: 91,
        },
        {
          text: 'どんな状況でもラグに頼る必要はないんですよ。',
          speaker: 'ayumi',
          id: 'S007-3',
          audioDurationFrames: 99,
          pauseAfter: 1.5,
        },
        {
          text: '今日覚えておきたいのは、ラグは"部分を取り出す仕組み"だということ。',
          speaker: 'ayumi',
          id: 'S008-1',
          audioDurationFrames: 163,
        },
        {
          text: '全部読ませたいなら向かないし、入力に収まるなら全文投入のほうが合理的。',
          speaker: 'ayumi',
          id: 'S008-2',
          audioDurationFrames: 185,
        },
        {
          text: 'パターンが少ないならテンプレ化で十分。',
          speaker: 'ayumi',
          id: 'S008-3',
          audioDurationFrames: 91,
        },
        {
          text: 'つまり、状況に合わせて柔軟に選ぶことが鍵です。',
          speaker: 'ayumi',
          id: 'S008-4',
          audioDurationFrames: 125,
          pauseAfter: 1.5,
        },
        {
          text: 'そして最後に……勢いでラグを導入してうまくいかなかった、という事例は本当に多いんです。',
          speaker: 'ayumi',
          id: 'S009-1',
          audioDurationFrames: 213,
        },
        {
          text: '大切なのは「本当に必要なのか」を落ち着いて見極めること。',
          speaker: 'ayumi',
          id: 'S009-2',
          audioDurationFrames: 148,
        },
        {
          text: 'ときには"ラグを使わない勇気"こそが、自社データ活用の成功をぐっと近づけてくれます。',
          speaker: 'ayumi',
          id: 'S009-3',
          audioDurationFrames: 216,
          pauseAfter: 5,
        }
      ],
    }
  ],
};
