import * as fs from 'fs';
import * as path from 'path';
import { getAudioDurationInSeconds } from 'get-audio-duration';

const SCRIPT_FILE = path.join(process.cwd(), 'script_final.md');
const VOICES_DIR = path.join(process.cwd(), 'public', 'voices');
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'data', 'slideshowConfig.ts');
const FPS = 30;

interface NarrationSegment {
  text: string;
  voicePath: string;
  audioDurationFrames: number;
}

interface SlideItem {
  id: string;
  slidePath: string;
  narrations: NarrationSegment[];
  totalDurationFrames: number;
}

interface ParsedScript {
  id: string;
  index: number;
  narration: string;
}

// script_final.mdを解析
function parseScriptFile(): ParsedScript[] {
  const content = fs.readFileSync(SCRIPT_FILE, 'utf-8');
  const lines = content.split('\n');
  const items: ParsedScript[] = [];

  // 各スライドIDの出現回数をカウント
  const idCounts: Record<string, number> = {};

  let currentId: string | null = null;

  for (const line of lines) {
    const idMatch = line.match(/\[([S]\d+)\]/);
    if (idMatch) {
      currentId = idMatch[1];
      continue;
    }

    if (line.trim().startsWith('NARRATOR:')) {
      continue;
    }

    if (currentId && line.trim() && !line.trim().startsWith('[')) {
      // このIDの出現回数をカウント
      if (!idCounts[currentId]) {
        idCounts[currentId] = 0;
      }
      idCounts[currentId]++;

      items.push({
        id: currentId,
        index: idCounts[currentId],
        narration: line.trim(),
      });
      currentId = null;
    }
  }

  return items;
}

// 音声ファイルの長さを取得
async function getAudioDuration(audioPath: string): Promise<number> {
  try {
    const duration = await getAudioDurationInSeconds(audioPath);
    return Math.ceil(duration * FPS);
  } catch (error) {
    console.error(`音声ファイルの読み込みに失敗: ${audioPath}`);
    return 0;
  }
}

// メイン処理
async function main() {
  console.log('=========================================');
  console.log('スライドショー設定ファイル生成');
  console.log('=========================================\n');

  const parsedItems = parseScriptFile();
  console.log(`解析結果: ${parsedItems.length}件\n`);

  // 同じスライドIDをグループ化
  const groupedBySlide: Record<string, ParsedScript[]> = {};
  for (const item of parsedItems) {
    if (!groupedBySlide[item.id]) {
      groupedBySlide[item.id] = [];
    }
    groupedBySlide[item.id].push(item);
  }

  const slides: SlideItem[] = [];
  let totalFrames = 0;

  // スライドIDをソートして処理
  const slideIds = Object.keys(groupedBySlide).sort();

  for (const slideId of slideIds) {
    const narrationItems = groupedBySlide[slideId];
    const narrations: NarrationSegment[] = [];
    let slideTotalFrames = 0;

    console.log(`\n${slideId}:`);

    for (const item of narrationItems) {
      const voiceFilePath = path.join(VOICES_DIR, `${item.id}-${item.index}.wav`);

      if (!fs.existsSync(voiceFilePath)) {
        console.error(`  ❌ 音声ファイルが見つかりません: ${item.id}-${item.index}.wav`);
        continue;
      }

      const audioDurationFrames = await getAudioDuration(voiceFilePath);
      console.log(`  ✓ ${item.id}-${item.index}: ${(audioDurationFrames / FPS).toFixed(2)}秒 (${audioDurationFrames}フレーム)`);

      narrations.push({
        text: item.narration,
        voicePath: `voices/${item.id}-${item.index}.wav`,
        audioDurationFrames,
      });

      slideTotalFrames += audioDurationFrames;
    }

    slides.push({
      id: slideId,
      slidePath: `slide/${slideId}.png`,
      narrations,
      totalDurationFrames: slideTotalFrames,
    });

    totalFrames += slideTotalFrames;
  }

  console.log(`\n総フレーム数: ${totalFrames} (${(totalFrames / FPS).toFixed(2)}秒)\n`);

  // TypeScriptファイルを生成
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const fileContent = `// This file is auto-generated by scripts/generateSlideshowConfig.ts
// Do not edit manually

import { SlideshowConfig } from '../types/slideshow';

export const slideshowConfig: SlideshowConfig = {
  bgmSrc: 'bgm/Floraria.mp3',
  bgmVolume: 0.2,
  slides: ${JSON.stringify(slides, null, 2)},
  totalFrames: ${totalFrames},
};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');

  console.log('=========================================');
  console.log('✅ スライドショー設定ファイルを生成しました');
  console.log(`出力先: ${OUTPUT_FILE}`);
  console.log('=========================================');
}

main();
