// This file is auto-generated by scripts/generateSlideshowConfig.ts
// Do not edit manually

import { SlideshowConfig } from '../types/slideshow';

export const slideshowConfig: SlideshowConfig = {
  bgmSrc: 'bgm/Floraria.mp3',
  bgmVolume: 0.2,
  slides: [
  {
    "id": "S001",
    "narration": "「自社データならRAGでしょ」と言われがちですが、実はそうとも限りません。まずは、その思い込みをそっとほどいていきましょう。",
    "slidePath": "slide/S001.png",
    "voicePath": "voices/S001.wav",
    "audioDurationFrames": 296
  },
  {
    "id": "S002",
    "narration": "よく耳にするのは、「RAGを入れないとダメですよね？」という声。けれど実際は、プロンプトだけで綺麗に回せるケースがたくさんあります。内容がパターン化できるなら、むしろRAGより精度が上がることも珍しくありません。",
    "slidePath": "slide/S002.png",
    "voicePath": "voices/S002.wav",
    "audioDurationFrames": 518
  },
  {
    "id": "S003",
    "narration": "最初に考えるのは、「AIに全部の情報を見てほしいのかどうか」。もし“全部読んだうえで判断してほしい”なら、部分検索であるRAGはあまり向いていません。全文を読ませるアプローチのほうが自然です。",
    "slidePath": "slide/S003.png",
    "voicePath": "voices/S003.wav",
    "audioDurationFrames": 492
  },
  {
    "id": "S004",
    "narration": "GPTやClaudeは10〜20万字、Geminiなら100万字以上入る時代です。実は、全文を入れてもコストはごくわずか。RAGを作り込むより、速くて安定していることが多いんですね。",
    "slidePath": "slide/S004.png",
    "voicePath": "voices/S004.wav",
    "audioDurationFrames": 461
  },
  {
    "id": "S005",
    "narration": "もしパターンが10〜20種類くらいなら、テンプレート化が最適です。業界別に作っておけば使い回しも簡単で、精度も運用も申し分ありません。",
    "slidePath": "slide/S005.png",
    "voicePath": "voices/S005.wav",
    "audioDurationFrames": 345
  },
  {
    "id": "S006",
    "narration": "“全部見たい”ならそのままプロンプトへ。",
    "slidePath": "slide/S006.png",
    "voicePath": "voices/S006.wav",
    "audioDurationFrames": 100
  },
  {
    "id": "S007",
    "narration": "RAGは万能ではありません。適材適所でこそ輝く技術です。「どの状況でもRAGが正解」というわけではないんです。",
    "slidePath": "slide/S007.png",
    "voicePath": "voices/S007.wav",
    "audioDurationFrames": 306
  },
  {
    "id": "S008",
    "narration": "RAGは“部分を取り出す技術”。",
    "slidePath": "slide/S008.png",
    "voicePath": "voices/S008.wav",
    "audioDurationFrames": 93
  },
  {
    "id": "S009",
    "narration": "勢いでRAGを作って失敗する例は少なくありません。まずは「本当に必要か」を落ち着いて見極めること。RAGを“使わない”判断こそ、自社データ活用の成功を近づける大事な一歩です。",
    "slidePath": "slide/S009.png",
    "voicePath": "voices/S009.wav",
    "audioDurationFrames": 499
  }
],
  totalFrames: 3110,
};
