// This file is auto-generated by scripts/generateSlideshowConfig.ts
// Do not edit manually

import { SlideshowConfig } from '../types/slideshow';

export const slideshowConfig: SlideshowConfig = {
  bgmSrc: 'bgm/Floraria.mp3',
  bgmVolume: 0.2,
  slides: [
  {
    "id": "S001",
    "slidePath": "slide/S001.png",
    "narrations": [
      {
        "text": "最近、Nano Banana ProっていうAIツールが話題になってるでしょ？",
        "voicePath": "voices/S001-1.wav",
        "audioDurationFrames": 143
      },
      {
        "text": "それが登場したことで、YouTubeのサムネイル制作の仕事がどうなるのかっていう話が出てきててね、",
        "voicePath": "voices/S001-2.wav",
        "audioDurationFrames": 205
      },
      {
        "text": "特に「サムネ制作の代行って、もう必要なくなるのかな？」っていう疑問が、",
        "voicePath": "voices/S001-3.wav",
        "audioDurationFrames": 189
      },
      {
        "text": "YouTuberとして気になるところなの。",
        "voicePath": "voices/S001-4.wav",
        "audioDurationFrames": 76
      },
      {
        "text": "私自身、サムネイルは全部自分で作ってきたから、実際に代行サービスを使ったことはないんだけど、",
        "voicePath": "voices/S001-5.wav",
        "audioDurationFrames": 229
      },
      {
        "text": "それでも制作側の目線で思うことは色々あるのよ。",
        "voicePath": "voices/S001-6.wav",
        "audioDurationFrames": 109
      }
    ],
    "totalDurationFrames": 966,
    "pauseAfter": 0.5
  },
  {
    "id": "S002",
    "slidePath": "slide/S002.png",
    "narrations": [
      {
        "text": "結論から言うとね、「言われた通りに見た目を整えるだけ」の仕事だったら、",
        "voicePath": "voices/S002-1.wav",
        "audioDurationFrames": 169
      },
      {
        "text": "たしかに厳しくなってくるかもしれないの。",
        "voicePath": "voices/S002-2.wav",
        "audioDurationFrames": 82
      },
      {
        "text": "Nano Banana Proの方が、安くて、早くて、しかも出来も悪くないからね。",
        "voicePath": "voices/S002-3.wav",
        "audioDurationFrames": 178
      },
      {
        "text": "でもね、サムネイルって、ただ綺麗に見せればいいわけじゃなくて、",
        "voicePath": "voices/S002-4.wav",
        "audioDurationFrames": 142
      },
      {
        "text": "ちゃんとクリックされるかどうか、つまり成果が伴うかがすごく大事なの。",
        "voicePath": "voices/S002-5.wav",
        "audioDurationFrames": 159
      },
      {
        "text": "視聴者が「この動画、見たい！」って思えるかどうかっていうところね。",
        "voicePath": "voices/S002-6.wav",
        "audioDurationFrames": 152
      }
    ],
    "totalDurationFrames": 897,
    "pauseAfter": 0.5
  },
  {
    "id": "S003",
    "slidePath": "slide/S003.png",
    "narrations": [
      {
        "text": "サムネイルの役割って、視覚的に動画の価値を一瞬で伝えることなのよ。",
        "voicePath": "voices/S003-1.wav",
        "audioDurationFrames": 163
      },
      {
        "text": "きれいさよりも、訴求力のある言葉や図の方が大事だったりするんだよね。",
        "voicePath": "voices/S003-2.wav",
        "audioDurationFrames": 149
      },
      {
        "text": "そして、面白いことにね、サムネイルって自由に作れるわけじゃないの。",
        "voicePath": "voices/S003-3.wav",
        "audioDurationFrames": 161
      },
      {
        "text": "動画の企画にすごく左右されるのよ。",
        "voicePath": "voices/S003-4.wav",
        "audioDurationFrames": 82
      },
      {
        "text": "内容とズレたサムネを作ると「釣り」になっちゃって、視聴者の信頼を損ねるしね。",
        "voicePath": "voices/S003-5.wav",
        "audioDurationFrames": 177
      },
      {
        "text": "逆に言えば、いいサムネを作るには、そもそもの企画がちゃんとしてないと難しいってことなのよ。",
        "voicePath": "voices/S003-6.wav",
        "audioDurationFrames": 206
      }
    ],
    "totalDurationFrames": 953,
    "pauseAfter": 0.5
  },
  {
    "id": "S004",
    "slidePath": "slide/S004.png",
    "narrations": [
      {
        "text": "最近の私の経験から言うと、トレンド動画、たとえば新しいAIツールの紹介とかって、",
        "voicePath": "voices/S004-1.wav",
        "audioDurationFrames": 213
      },
      {
        "text": "そこまでサムネイルに凝らなくても結構見てもらえるの。",
        "voicePath": "voices/S004-2.wav",
        "audioDurationFrames": 108
      },
      {
        "text": "でもね、トレンドに頼らないエバーグリーンな動画だと、",
        "voicePath": "voices/S004-3.wav",
        "audioDurationFrames": 110
      },
      {
        "text": "しっかり「この動画、見る価値あるよ」って伝える工夫が必要になってくるのよ。",
        "voicePath": "voices/S004-4.wav",
        "audioDurationFrames": 178
      },
      {
        "text": "そういう意味では、サムネイルって見た目を作るだけの話じゃなくて、",
        "voicePath": "voices/S004-5.wav",
        "audioDurationFrames": 137
      },
      {
        "text": "情報をどう整理して、どう見せるかっていう設計の話なの。",
        "voicePath": "voices/S004-6.wav",
        "audioDurationFrames": 137
      },
      {
        "text": "実際、昔からある『ノンデザイナーズ・デザインブック』なんかを読むと、そのロジックがすごくわかりやすいよ。",
        "voicePath": "voices/S004-7.wav",
        "audioDurationFrames": 246
      }
    ],
    "totalDurationFrames": 1144,
    "pauseAfter": 0.5
  },
  {
    "id": "S005",
    "slidePath": "slide/S005.png",
    "narrations": [
      {
        "text": "だからね、Nano Banana Proで一見よさげなサムネが作れても、",
        "voicePath": "voices/S005-1.wav",
        "audioDurationFrames": 138
      },
      {
        "text": "訴求の中身が曖昧だったり、見る人に価値が伝わらなければ意味がないの。",
        "voicePath": "voices/S005-2.wav",
        "audioDurationFrames": 161
      },
      {
        "text": "AIに画像を作らせるにも、どんな価値を伝えたいかを自分でしっかり言語化しないとダメってことね。",
        "voicePath": "voices/S005-3.wav",
        "audioDurationFrames": 215
      }
    ],
    "totalDurationFrames": 529,
    "pauseAfter": 0.5
  },
  {
    "id": "S006",
    "slidePath": "slide/S006.png",
    "narrations": [
      {
        "text": "結局のところ、「サムネ制作代行」っていう仕事も、",
        "voicePath": "voices/S006-1.wav",
        "audioDurationFrames": 127
      },
      {
        "text": "ただ作るだけならAIで済んじゃうかもしれない。",
        "voicePath": "voices/S006-2.wav",
        "audioDurationFrames": 100
      },
      {
        "text": "でも、動画の意図やターゲットをちゃんと理解して、",
        "voicePath": "voices/S006-3.wav",
        "audioDurationFrames": 113
      },
      {
        "text": "より良くする提案ができる人なら、これからも選ばれる可能性はあると思うの。",
        "voicePath": "voices/S006-4.wav",
        "audioDurationFrames": 164
      },
      {
        "text": "ただし、そういう人ってもう、ほとんどディレクターとかプロデューサーの領域よね。",
        "voicePath": "voices/S006-5.wav",
        "audioDurationFrames": 170
      },
      {
        "text": "めちゃくちゃレベルの高い話だけど、そういう付加価値を出せる人が生き残っていくんじゃないかな。",
        "voicePath": "voices/S006-6.wav",
        "audioDurationFrames": 189
      }
    ],
    "totalDurationFrames": 878,
    "pauseAfter": 0.5
  },
  {
    "id": "S007",
    "slidePath": "slide/S007.png",
    "narrations": [
      {
        "text": "まとめると、AIで「見た目を整える」ことは簡単になったけど、",
        "voicePath": "voices/S007-1.wav",
        "audioDurationFrames": 150
      },
      {
        "text": "「何を伝えるか」っていう企画の部分に向き合えるかどうかが、",
        "voicePath": "voices/S007-2.wav",
        "audioDurationFrames": 129
      },
      {
        "text": "これからのクリエイターやデザイナーの価値を左右していくんじゃないかなって思うんだ。",
        "voicePath": "voices/S007-3.wav",
        "audioDurationFrames": 157
      },
      {
        "text": "AIは味方になるけど、それをちゃんと活かすためには、",
        "voicePath": "voices/S007-4.wav",
        "audioDurationFrames": 119
      },
      {
        "text": "やっぱり人の意図が大事になってくるってことね。",
        "voicePath": "voices/S007-5.wav",
        "audioDurationFrames": 95
      }
    ],
    "totalDurationFrames": 740,
    "pauseAfter": 3
  }
],
  totalFrames: 6107,
};
